name: "AniDB"
guid: "a2b2a7ed-aa28-4521-a64a-63d86901f246"
imageUrl: https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anidb.png
version: 9
targetAbi: "10.9.4.0"
framework: "net8.0"
owner: "jellyfin"
overview: "AniDB metadata provider"
description: >
  AniDB metadata provider

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AniDB.dll"
changelog: |-
  - Map tag "18 restricted" to parental rating NC-17 (#48) @nalsai
  - Strip the year from the name for finding matches (#55) @nalsai
  - Add n-apostrophe replacement (#56) @nalsai
  - Add wo replacement (#57) @nalsai
